import {
  ActionIcon,
  Alert,
  Badge,
  Button,
  Paper,
  Select,
  SegmentedControl,
  TextInput,
  createTheme,
  type CSSVariablesResolver,
} from "@mantine/core";
import classes from "./theme.module.css";

const sans = '"Manrope Variable", ui-sans-serif, system-ui, sans-serif';
const mono = '"SFMono-Regular", Consolas, "Liberation Mono", ui-monospace, monospace';

const colors = {
  light: {
    canvas: "#e9ddcb",
    paper: "#fff9ee",
    paperMuted: "#f4eadb",
    paperStrong: "#e2d1bd",
    ink: "#2d1f19",
    muted: "#68594f",
    subtle: "#786a60",
    line: "#d0bda8",
    lineStrong: "#91786a",
    accent: "#bd6b49",
    accentBorder: "#75432f",
    sage: "#126d69",
    sageSurface: "#d9ece7",
    sky: "#416c7b",
    rust: "#a94436",
    rustSurface: "#f4d9cf",
    panel: "#33231d",
    focus: "#126d69",
    shadow: "rgba(63, 40, 29, 0.18)",
  },
  dark: {
    canvas: "#13100f",
    paper: "#211a17",
    paperMuted: "#1b1614",
    paperStrong: "#33251f",
    ink: "#f4e4ce",
    muted: "#cdb9a5",
    subtle: "#ad9988",
    line: "#49392f",
    lineStrong: "#755c4d",
    accent: "#d98a62",
    accentBorder: "#a95f3d",
    sage: "#69c1b5",
    sageSurface: "#1c3632",
    sky: "#8fb8c4",
    rust: "#f08770",
    rustSurface: "#42251f",
    panel: "#0b0908",
    focus: "#69c1b5",
    shadow: "rgba(0, 0, 0, 0.42)",
  },
} as const;

type SemanticColors = (typeof colors)[keyof typeof colors];

function semanticVariables(value: SemanticColors) {
  return {
    "--ds-canvas": value.canvas,
    "--ds-paper": value.paper,
    "--ds-paper-muted": value.paperMuted,
    "--ds-paper-strong": value.paperStrong,
    "--ds-ink": value.ink,
    "--ds-muted": value.muted,
    "--ds-subtle": value.subtle,
    "--ds-line": value.line,
    "--ds-line-strong": value.lineStrong,
    "--ds-accent": value.accent,
    "--ds-accent-border": value.accentBorder,
    "--ds-accent-surface": `color-mix(in srgb, ${value.accent} 14%, ${value.paper})`,
    "--ds-sage": value.sage,
    "--ds-sage-surface": value.sageSurface,
    "--ds-sky": value.sky,
    "--ds-rust": value.rust,
    "--ds-rust-surface": value.rustSurface,
    "--ds-panel": value.panel,
    "--ds-focus": value.focus,
    "--ds-shadow-color": value.shadow,
    "--ds-glass": `color-mix(in srgb, ${value.paper} 44%, transparent)`,
    "--ds-glass-strong": `color-mix(in srgb, ${value.paper} 64%, transparent)`,
    "--ds-glass-overlay": `color-mix(in srgb, ${value.paper} 86%, transparent)`,
    "--ds-glass-line": `color-mix(in srgb, ${value.lineStrong} 44%, transparent)`,
    "--ds-glass-highlight": `color-mix(in srgb, ${value.paper} 88%, transparent)`,
    "--ds-glass-refraction": `color-mix(in srgb, ${value.sky} 16%, transparent)`,
  };
}

export const cssVariablesResolver: CSSVariablesResolver = () => ({
  variables: {
    "--ds-font-sans": sans,
    "--ds-font-mono": mono,
    "--ds-space-1": "4px",
    "--ds-space-2": "8px",
    "--ds-space-3": "12px",
    "--ds-space-4": "18px",
    "--ds-space-5": "24px",
    "--ds-radius-xs": "3px",
    "--ds-radius-sm": "6px",
    "--ds-radius-md": "10px",
    "--ds-radius-lg": "14px",
    "--ds-radius-xl": "18px",
    "--ds-motion-fast": "120ms",
    "--ds-motion-standard": "180ms",
    "--ds-motion-easing": "cubic-bezier(0.2, 0, 0, 1)",
    "--ds-glass-blur": "26px",
    "--ds-glass-saturate": "1.28",
    "--ds-glass-brightness": "1.04",
    "--ds-glass-contrast": "1.02",
    "--ds-glass-sheen": "linear-gradient(135deg, color-mix(in srgb, var(--ds-glass-highlight) 44%, transparent), transparent 38%, color-mix(in srgb, var(--ds-glass-refraction) 40%, transparent) 68%, transparent)",
    "--ds-surface-inset": "var(--ds-paper-muted)",
    "--ds-surface-work": "var(--ds-paper)",
    "--ds-surface-work-header": "color-mix(in srgb, var(--ds-paper-muted) 88%, var(--ds-paper))",
    "--ds-work-line": "color-mix(in srgb, var(--ds-line-strong) 72%, var(--ds-line))",
    "--ds-shadow-inset": "inset 0 1px 2px color-mix(in srgb, var(--ds-ink) 9%, transparent), inset 0 -1px 0 color-mix(in srgb, var(--ds-glass-highlight) 72%, transparent)",
    "--ds-shadow-work": "0 1px 0 color-mix(in srgb, var(--ds-line-strong) 44%, transparent), 0 10px 22px -20px color-mix(in srgb, var(--ds-ink) 38%, transparent), inset 0 1px 0 color-mix(in srgb, var(--ds-glass-highlight) 78%, transparent)",
    "--ds-shadow-control": "0 8px 18px -14px color-mix(in srgb, var(--ds-ink) 50%, transparent)",
    "--ds-shadow-control-hover": "0 12px 24px -16px color-mix(in srgb, var(--ds-ink) 58%, transparent)",
    "--ds-shadow-float": "0 24px 64px -28px color-mix(in srgb, var(--ds-ink) 52%, transparent), 0 8px 22px -16px color-mix(in srgb, var(--ds-sky) 40%, transparent), inset 0 1px 0 var(--ds-glass-highlight), inset 0 -1px 0 var(--ds-glass-refraction)",
  },
  light: semanticVariables(colors.light),
  dark: semanticVariables(colors.dark),
});

const inputClassNames = {
  label: classes.inputLabel,
  input: classes.input,
  error: classes.inputError,
};

export const theme = createTheme({
  primaryColor: "sage",
  primaryShade: 7,
  autoContrast: true,
  luminanceThreshold: 0.45,
  black: colors.light.ink,
  white: colors.light.paper,
  colors: {
    honey: ["#fbf1ec", "#f5dfd5", "#ebc3b1", "#dfa288", "#d08362", "#bd6b49", "#a7593b", "#8d4c35", "#75432f", "#5f3729"],
    sage: ["#ecf8f5", "#d9ece7", "#b5ddd5", "#87c8bd", "#58aea4", "#319188", "#187b75", "#126d69", "#105754", "#0e4543"],
    sky: ["#f0f7f8", "#dce9eb", "#bfd8de", "#99c0ca", "#73a7b4", "#588d9c", "#416c7b", "#345866", "#2b4853", "#243a43"],
    rust: ["#fff3ed", "#fbe2d6", "#f3c1aa", "#e99b79", "#de7952", "#c85f3d", "#a94b31", "#873d2b", "#6d3327", "#572b23"],
  },
  fontFamily: sans,
  fontFamilyMonospace: mono,
  headings: { fontFamily: sans, fontWeight: "700", textWrap: "balance" },
  defaultRadius: "md",
  radius: { xs: "3px", sm: "6px", md: "10px", lg: "14px", xl: "18px" },
  spacing: { xs: "8px", sm: "12px", md: "18px", lg: "24px", xl: "34px" },
  breakpoints: { xs: "30em", sm: "43.75em", md: "56.25em", lg: "75em", xl: "90em" },
  respectReducedMotion: true,
  cursorType: "pointer",
  components: {
    Button: Button.extend({
      defaultProps: { variant: "default", radius: "md" },
      classNames: { root: classes.buttonRoot, label: classes.buttonLabel, section: classes.buttonSection },
    }),
    ActionIcon: ActionIcon.extend({
      defaultProps: { variant: "default", radius: "md" },
      classNames: { root: classes.actionIconRoot },
    }),
    SegmentedControl: SegmentedControl.extend({
      defaultProps: { radius: "md", withItemsBorders: false },
      classNames: { root: classes.segmentedRoot, label: classes.segmentedLabel, indicator: classes.segmentedIndicator },
    }),
    Paper: Paper.extend({ defaultProps: { radius: "md" }, classNames: { root: classes.paperRoot } }),
    Alert: Alert.extend({
      defaultProps: { radius: "md", variant: "light" },
      classNames: { root: classes.alertRoot, title: classes.alertTitle, message: classes.alertMessage },
    }),
    Badge: Badge.extend({
      defaultProps: { radius: "sm", variant: "light", color: "sage" },
      classNames: { root: classes.badgeRoot, label: classes.badgeLabel },
    }),
    TextInput: TextInput.extend({ classNames: inputClassNames }),
    Select: Select.extend({ classNames: { ...inputClassNames, dropdown: classes.dropdown, option: classes.option } }),
  },
});
